import Head from "next/head";
import Image from "next/image";

import classnames from "classnames";

import Flags from "country-flag-icons/react/3x2";

// CSS file, required for flags to work with CSS technique
import "country-flag-icons/3x2/flags.css";
import styles from "../styles/Home.module.css";

export default function Home({}) {
  // const Flag = Flags["GB"]; // know that all flags render as components themselves not props of a Flag component

  const countryTestCode = "GB";
  const countryTestName = "United Kingdom";

  const countryCode = "gb";

  // Dynamic Component Approach
  const Flag = ({ countryCode }) => {
    const FlagComponent = Flags[countryCode.toUpperCase()];
    return <FlagComponent style={{ width: "60px", marginTop: "15px" }} />;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Flags for Geo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Flags for Geo</h1>

        {/* solve inability to add title with country name by enclosing in div */}
        <div title={countryTestName}>
          <Flag countryCode={countryCode} />
        </div>

        {/* Manual Component Approach */}
        {/* <Flag title="GB" style={{ width: "48px", marginTop: "15px" }} />

        <div
          className={"flag:" + "US"}
          style={{ marginTop: "30px", width: "60px", height: "40px" }}
        /> */}

        {/* CSS method -- better support for direct JSX integration? */}
        <div
          className={classnames(styles.countryflag, "flag:" + countryTestCode)}
          title={countryTestName}
          style={{ marginTop: "30px", width: "60px", height: "40px" }}
        />

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
